### PR TITLE
Resolve #16 and Resolve #17

### LINKED ISSUE #16: [Feature Request] Use Miniart instead of Fanart for the Page
Because the titles are not shown, maybe you can use the Mini-Art from Jellyfin for the Pages.

### LINKED ISSUE #17: [ISSUE] Backgrounds are not showing in the title view
When you open the View of a title, there is no background of the title.

### PR DESCRIPTION
**Pull request by stephenb10**
Set the default image for titles to primary and added option to use backdrop instead.

### CODE REVIEW

**Comment by stephenb10** [comment]
Screen Shot 2021-05-16 at 9 22 12 pm
Screen Shot 2021-05-16 at 9 22 27 pm

**Comment by stephenb10** [comment]
Screen Shot 2021-05-16 at 9 25 22 pm

Screen Shot 2021-05-16 at 9 32 30 pm

**Review by noahkamara — COMMENTED** [review]
Hey,
Is there any reason for not using colorhashes (provided through the api) to display blurred backgrounds? Those should perform better than using images.

it would also be better to use smaller images than the default 600px width since they will be blurred anyway

**Comment by stephenb10** [comment]
Oh i didn't know of that, is that the blur field when fetching images?

**Comment by noahkamara** [comment]
The MediaItem ApiModel contains a field `imageBlurHashes`

https://github.com/ABJC/ABJC-tvOS/blob/main/ABJC/APIModels/Media%20Item/MediaItem.swift

It’s a dictionary with Imagetype as key and a blurhash as value.
There are multiple swift blurhash librarie. See https://blurha.sh/ for more info on blurhashes

**Comment by noahkamara** [comment]
I've made the changes in branch pr/20

- Blurhashes instead of manually blurring images
- posterType instead of boolean (to make a future feature easier to implement)

**Pull request closed without merging**
