### PR TITLE
UI Changes

### PR DESCRIPTION
**Pull request by stephenb10**
This PR aims to redesign some of the initial views

- [x] Server Selection View
- [x] Manual Server Selection View
- [x] Credentials View
- [x] User Select View
- [x] Allow for switching users

Server Selection View:
Simulator Screen Shot - Apple TV 4K (at 1080p) (2nd generation) - 2021-06-04 at 15 02 00

### CODE REVIEW

**Comment by noahkamara** [comment]
Looks very nice 👍🏾 but we should probably use the ABJC not the Jellyfin logo because this might ["make the average user think [ABJC is] associated with the project"](https://jellyfin.org/docs/general/contributing/branding.html)

I'll add the logos to the repository

**Comment by stephenb10** [comment]
Adding in user selection once choosing a server.

This should hope to fix #30 

User Selection

Will still need a few things, switching users once logged in and a way to determine if the server is http or https, or ask for that when selecting a server.

**Comment by stephenb10** [comment]
Will need to rework the logic with logging out so it saves the server but not the user and transitions to the user selection view.

Also I don't seem to have the newly added assets for ABJC in my xcassets.

Views might still need a little polish but any feedback would be appreciated :)

Credentials View:
Credentials View

Manual Selection View:
Manual Selection View

**Comment by noahkamara** [comment]
> Also I don't seem to have the newly added assets for ABJC in my xcassets.

I added the assets in the "Assets" folder in the main branch. I just added them to xcassets. You can merge main into your pull request to apply the changes 😄 

The UI looks great! Have you tried it out with both light and dark mode? (The background might be a problem in light, when text is black)

**Comment by stephenb10** [comment]
> (The background might be a problem in light, when text is black)

Does tvOS have a light and dark mode? I just assumed that it was one appearance but i will add in the dark variation.

**Comment by stephenb10** [comment]
Added a check for if logged in from the session, instead of removing the Jellyfin from the session we toggle the logged in value. Not sure if there is a better approach to this.

Now when logging out it switches to the User Select View but the app seems to ignore controls for some reason but it is not frozen. Once this is fixed the PR will be ready for review.

**Comment by stephenb10** [comment]
> Now when logging out it switches to the User Select View but the app seems to ignore controls for some reason but it is not frozen.

Needed to nest the view in a navigation link when showing the view on its own, focus and controls now working.

Logging out is functioning correctly, PR is now ready for review.

**Review by noahkamara — APPROVED** [review]

**Pull request merged**
