### PR TITLE
Performant Collection Views

### LINKED ISSUE #19: [ISSUE] Improve performance
The App is darn slow and, in cause of that, partly not functional.

### PR DESCRIPTION
**Pull request by noahkamara**
Using UICollectionView instead of SwiftUIs LazyStacks should greatly improve performance

resolves #19

### CODE REVIEW

**Comment by noahkamara** [comment]
@stevebyatt10 can you try this out on your ATV and check wether performance is increased compared to the [main branch](https://github.com/ABJC/ABJC-tvOS/tree/main)?

**Comment by stevebyatt10** [comment]
Still lags very slightly sometimes but performance is much better.

**Comment by noahkamara** [comment]
Great! I also checked URLImage vs AsyncImage (iOS 15) and found that AsyncImage performs better.

Performance increases should be most noticeable for users with large to very large libraries

**Comment by noahkamara** [comment]
resolves #19
resolves #34

**Pull request merged**
